list: $/eev/corpcore/models/contact/columns.yaml
modelClass: EEV\CorpCore\Models\Contact
title: ContactController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eev/corpcore/contactcontroller/update/:id'
